language: java
matrix:
  include:
  - jdk: openjdk9
addons:
  sonarcloud:
    organization: exasol
    token:
      secure: "r3gTcaYGDycgKyWcfUYAh/61IjVceRR3C//35KzcMFas9bIEacm12B4tKCQ8emqI+xPZUCmf7b9rWTxvmsJIXzK4Vsyj1ipYR/IaffoPYalWZkqoUDmljmwqlLg21Y2y/oXejL0us3q+DcwgauI0jM8E/U/L0dymrBd69ZUguZXXzoNF7isIo3msrOAywLxuiQ6oHGlLFgUNC2GDi5a2LSM4TCputqAyUhozTo+d+/ZVbb796h9PaY1K0oFNyOCD7/CGCLgj1RIgq4jFzINxl0TqbRSM64vrPO9Fd9+pMO/zNOKY0q5ohjOfjV0ASDxUAM8X2tfDtK2OdjBOcnFLrrlJSXU2sJATUKV0JqMtvO/VI6t+Gb6tGdF7R0AOZhRj6Num78W9VfovoO0XCrT9GVdC5DnwUplZsNlJz4cEUyP+REUWiAHfHag+HxBwvKJ2AwpFh4LKjpr5Z8behj+RSsmkC/2XJVau4vp5F1nLuZ6K9nl4zRdYQi2ychmC0dLuUjKNVvo71tBHaQc7TK9XpY11J5pzppkNsDpNy3czEr8KsMxyTuuu4wuP041HKP+HgNEjtY70p6F5g2mwRKVcrLBxBf81zHLpZzbU+Hm5Dthxmyoa2ZAOjkMAoas4F2V4SZkGd6eIk4IopFvpCgrpw6pAzw87yHQIoy5yChRBDdM="
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
  - "$HOME/.m2"