language: java
matrix:
  include:
  - jdk: openjdk9
addons:
  sonarcloud:
    organization: exasol
    token:
      secure: L/Qvaywu1ELUeBPsWn/tZExTWwhdFtCZ1z53PX+YBVxnfK7hwa8RMkr52aiYNhukeqAany18Pl+P/MDUOUVFh+1kEjvDXr4FYMjYF1B625o0ZtKoRNl2cJT5BJL4YmPPVrQpPIRpGEfGZNeCJmEXNUweQfRTz8gKuyopIFW292FBAEkhCf3vh+qtV+4vpJ9QnIi9kjgo+E4MkcACHVOyNWsdk4pxeyb5zwLtxEtge3U1qJuwmdlwaagVnhq4OEQCRxR4M7nvkbOytv3EfgQ6/GFI9MoXJHPLVaP0OqB4GxUVRvzeSMJ/oR89HUYNZViVSXYauvLMaABHzzrSVw9o8gpld1PQgibQAvhcsqqsVa/r4izKvyROau5GSd54LSLWQRqa9RGn0Th3Zfn/KWonTQ56eTWFt0FF0RrZil9T/GBTwhtR9pdKIG+iLed016ja3jeJ0MJme7qRiiIfuuazWP4asZA/W8oA34d9wDa4adFuVVFm0mxrOlMov3CjTJapU/7Ma9gcwkAsCHjhKVPDrqhmnKBjJR/OEuaRPkn81oiKNeI7amk/7iMPrOfZKfi/730T8P5e+vHxH4jRoegKXjm4zQBOfIStMINO7y+ZiPDvAxbRiolLDIYmV1QXHtJHM3NOuF08t0168UPqMdMqeA1gc2i5V60AX+icuUu46gk=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
  - "$HOME/.m2"
